# Generated by Django 5.0.3 on 2024-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_theme_defaultuser_portfolio_theme_dark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hero',
            field=models.CharField(max_length=255),
        ),
    ]
