services:

  portfolio-backend:
    container_name: portfolio-backend
    build: .
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    env_file:
      - .env.dev
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - .:/usr/src/app/