# Generated by Django 5.0.3 on 2024-07-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subTitle', models.CharField(max_length=255)),
                ('showLocation', models.BooleanField(default=True)),
                ('showSocials', models.BooleanField(default=True)),
                ('showEmail', models.BooleanField(default=True)),
                ('showResume', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField(unique=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='svg/')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('todo', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('organisation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('menuName', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=511, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('idList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.list')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=255)),
                ('hero', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('logo', models.FileField(upload_to='logos/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('footer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.footer')),
                ('theme_dark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dark_theme', to='user.theme')),
                ('theme_light', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='light_theme', to='user.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('index', models.IntegerField(unique=True)),
                ('url', models.URLField(unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('svg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.svg')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
