# Generated by Django 5.0.3 on 2024-07-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
