# Generated by Django 5.0.3 on 2024-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creditsShortUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='creditsUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
