# Generated by Django 5.0.3 on 2024-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
