# Generated by Django 5.0.3 on 2024-07-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_workitem_showexperiences_workitem_showprojects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='experience',
            new_name='experiences',
        ),
    ]
