# Generated by Django 5.0.3 on 2026-07-11 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_about_description_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Teinte du tag au format #RRGGBB. Vide = style par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
    ]
