# Generated by Django 5.0.3 on 2026-07-11 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_technology_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('github', 'GitHub'), ('website', 'Website'), ('appstore', 'App Store'), ('playstore', 'Play Store'), ('docs', 'Documentation'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, default='', help_text='Texte affiché ; vide = libellé par défaut du kind.', max_length=255)),
                ('index', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='user.project')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
