# Generated by Django 5.0.3 on 2026-07-11 13:30

from django.db import migrations


def forwards(apps, schema_editor):
    """Convert each non-empty Project.url into a `website` ProjectLink."""
    Project = apps.get_model('user', 'Project')
    ProjectLink = apps.get_model('user', 'ProjectLink')
    for project in Project.objects.exclude(url__isnull=True).exclude(url=''):
        ProjectLink.objects.get_or_create(
            project=project, kind='website', url=project.url,
            defaults={'index': 0},
        )


def backwards(apps, schema_editor):
    """Remove the `website` links that were generated from Project.url."""
    ProjectLink = apps.get_model('user', 'ProjectLink')
    ProjectLink.objects.filter(kind='website').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_projectlink'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
