# Generated by Django 5.0.3 on 2026-07-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_convert_project_url_to_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.technology')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='projecttechnology',
            constraint=models.UniqueConstraint(fields=('project', 'technology'), name='unique_project_technology'),
        ),
    ]
