# Generated by Django 5.0.3 on 2026-07-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_switch_technologies_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Fichier icône (SVG ou PNG) ; vide = icône par défaut du kind.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.file'),
        ),
    ]
