# Generated by Django 5.0.3 on 2026-07-11 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_add_projectlink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Teinte du lien au format #RRGGBB (texte, bordure, icône SVG). Vide = style par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
    ]
