# Generated by Django 5.0.3 on 2026-07-11 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_add_projectlink_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Teinte de l'icône au format #RRGGBB. Vide = couleur du thème.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
    ]
