# Generated by Django 5.0.3 on 2026-07-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_add_social_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.experience')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.technology')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='experiencetechnology',
            constraint=models.UniqueConstraint(fields=('experience', 'technology'), name='unique_experience_technology'),
        ),
    ]
