# Generated by Django 5.0.3 on 2026-07-11 15:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_switch_experience_technologies_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('background', models.CharField(help_text='Token --color-background au format #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('text', models.CharField(help_text='Token --color-text au format #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('primary', models.CharField(help_text='Token --color-primary au format #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Thème actif ; vide = tokens par défaut du frontend.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.theme'),
        ),
    ]
