# Generated by Django 5.0.3 on 2026-07-11 15:41

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_add_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="Timezone IANA (ex. 'Europe/Paris') pour l'horloge du footer ; vide = heure locale du visiteur.", max_length=64, validators=[user.models.validate_timezone]),
        ),
    ]
