# Generated by Django 5.0.3 on 2026-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_add_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Badge court affiché sur la carte (ex. "Secondaire", "Pro"). Vide = pas de badge.', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='isNew',
            field=models.BooleanField(default=False, help_text='Affiche un ruban "Nouveau" sur la carte.'),
        ),
        migrations.AddField(
            model_name='project',
            name='metric',
            field=models.CharField(blank=True, default='', help_text='Métrique courte affichée sous la description (ex. "~6k € ARR", "10k users").', max_length=100),
        ),
    ]
