# Generated by Django 5.0.3 on 2026-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_add_project_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='healthCheckedAt',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='healthFailures',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Échecs consécutifs (anti-faux-négatifs).'),
        ),
        migrations.AddField(
            model_name='project',
            name='healthUp',
            field=models.BooleanField(default=None, editable=False, help_text='Dernier état connu ; null = jamais vérifié.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='healthUrl',
            field=models.URLField(blank=True, help_text='Endpoint de santé à vérifier périodiquement. Vide = pas de check.', null=True),
        ),
    ]
