# Generated by Django 5.0.3 on 2026-07-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_add_project_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
