# Generated by Django 5.0.3 on 2026-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='iconFramed',
            field=models.BooleanField(default=True, help_text="Encadre l'icône (tuile + bordure). Décocher pour une icône sans cadre."),
        ),
    ]
