# Generated by Django 5.0.3 on 2026-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_add_project_icon_framed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='color',
        ),
    ]
