# Generated by Django 5.0.3 on 2026-07-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_social_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='iconPosition',
            field=models.CharField(choices=[('before', 'Avant le libellé'), ('after', 'Après le libellé')], default='before', help_text="Position de l'icône par rapport au libellé.", max_length=10),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Fichier icône (SVG ou PNG) ; vide = aucune icône.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.file'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Texte affiché ; vide = "Open".', max_length=255),
        ),
    ]
