# Generated by Django 5.0.3 on 2026-07-12 12:58

import django.core.validators
import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_add_projectlink_icon_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inProgress',
            field=models.BooleanField(default=False, help_text='Show a "Work in progress" badge on the card.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Short badge shown on the card (e.g. "Side project", "Pro"). Empty = no badge.', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='healthFailures',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Consecutive failures (guards against false negatives).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='healthUp',
            field=models.BooleanField(default=None, editable=False, help_text='Last known state; null = never checked.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='healthUrl',
            field=models.URLField(blank=True, help_text='Health endpoint to probe periodically. Empty = no check.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='iconFramed',
            field=models.BooleanField(default=True, help_text='Frame the icon (tile + border). Uncheck for a frameless icon.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='isNew',
            field=models.BooleanField(default=False, help_text='Show a "New" badge on the card.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metric',
            field=models.CharField(blank=True, default='', help_text='Short metric shown under the description (e.g. "~6k € ARR", "10k users").', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Link hue as #RRGGBB (text, border, SVG icon). Empty = default style.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Icon file (SVG or PNG); empty = no icon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.file'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='iconPosition',
            field=models.CharField(choices=[('before', 'Before label'), ('after', 'After label')], default='before', help_text='Icon position relative to the label.', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Displayed text; empty = "View".', max_length=255),
        ),
        migrations.AlterField(
            model_name='technology',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Tag hue as #RRGGBB. Empty = default style.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.CharField(help_text='--color-background token as #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=models.CharField(help_text='--color-primary token as #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.CharField(help_text='--color-text token as #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Active theme; empty = frontend default tokens.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.theme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="IANA timezone (e.g. 'Europe/Paris') for the footer clock; empty = visitor's local time.", max_length=64, validators=[user.models.validate_timezone]),
        ),
    ]
