# Generated by Django 5.0.3 on 2026-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_add_project_in_progress_and_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imageFit',
            field=models.CharField(choices=[('cover', 'Cover (fill, may crop)'), ('contain', 'Contain (whole image, padded)')], default='cover', help_text='How the image fills the icon frame (cover = fill/crop, contain = whole image).', max_length=10),
        ),
    ]
