# Generated by Django 5.0.3 on 2026-07-13 10:23

import user.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_add_project_image_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=user.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
