# Generated by Django 5.0.3 on 2026-07-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_file_overwrite_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='user.file'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imageResponsive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imageResponsive', to='user.file'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='backgroundImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.file'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.file'),
        ),
        migrations.AlterField(
            model_name='social',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logo', to='user.file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume', to='user.file'),
        ),
    ]
